use meossgdb;

DROP TABLE IF EXISTS OUTWAREHOUSE;
DROP TABLE IF EXISTS INWAREHOUSE;
DROP TABLE IF EXISTS PLACING_ORDER;
DROP TABLE IF EXISTS DELIVERY;
DROP TABLE IF EXISTS ORDER_LIST;
DROP TABLE IF EXISTS MEMBER_ORDER;
DROP TABLE IF EXISTS STOCK;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS ADMIN;

DROP TABLE IF EXISTS ADMIN;
CREATE TABLE IF NOT EXISTS ADMIN
(
    ID    VARCHAR(50) NOT NULL COMMENT '관리자번호',
    NAME    VARCHAR(50) NOT NULL COMMENT '이름',
    ASSOCIATION    VARCHAR(50) NOT NULL COMMENT '소속',
    PASSWORD    VARCHAR(50) NOT NULL COMMENT '비밀번호',
    PRIMARY KEY ( ID )
    ) COMMENT = 'ADMIN';


DROP TABLE IF EXISTS MEMBER;
CREATE TABLE IF NOT EXISTS MEMBER
(
    ID    VARCHAR(50) NOT NULL COMMENT '회원번호',
    NAME    VARCHAR(50) NOT NULL COMMENT '이름',
    PHONE    VARCHAR(50) COMMENT '전화번호',
    ADDRESS    VARCHAR(50) NOT NULL COMMENT '주소',
    PASSWORD    VARCHAR(50) NOT NULL COMMENT '비밀번호',
    PRIMARY KEY ( ID )
    ) COMMENT = 'MEMBER';


DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID    VARCHAR(50) NOT NULL COMMENT '상품번호',
    NAME    VARCHAR(50) NOT NULL COMMENT '이름',
    PRICE    INTEGER NOT NULL COMMENT '가격',
    SIZE    VARCHAR(50) COMMENT '사이즈',
    COLOR    VARCHAR(50) COMMENT '색상',
    AVAILABILITY    VARCHAR(10) NOT NULL COMMENT '판매여부',
    PRIMARY KEY ( ID )
    ) COMMENT = 'PRODUCT';


DROP TABLE IF EXISTS STOCK;
CREATE TABLE IF NOT EXISTS STOCK
(
    PRODUCT_ID    VARCHAR(50) NOT NULL COMMENT '상품번호',
    COUNT    INTEGER COMMENT '수량',
    PRIMARY KEY ( PRODUCT_ID ),
    FOREIGN KEY ( PRODUCT_ID ) REFERENCES PRODUCT (ID)
    ) COMMENT = 'STOCK';


DROP TABLE IF EXISTS MEMBER_ORDER;
CREATE TABLE IF NOT EXISTS MEMBER_ORDER
(
    ID           VARCHAR(50) NOT NULL COMMENT '주문번호',
    MEMBER_ID    VARCHAR(50) NOT NULL COMMENT '회원번호',
    PRIMARY KEY ( ID ),
    FOREIGN KEY ( MEMBER_ID ) REFERENCES MEMBER (ID)
    ) COMMENT = 'ORDER';


DROP TABLE IF EXISTS ORDER_LIST;
CREATE TABLE IF NOT EXISTS ORDER_LIST
(
    ORDER_ID VARCHAR(50) NOT NULL COMMENT '주문번호',
    PRODUCT_ID    VARCHAR(50) NOT NULL COMMENT '상품번호',
    COUNT    INTEGER NOT NULL COMMENT '수량',
    PRIMARY KEY ( ORDER_ID,PRODUCT_ID ),
    FOREIGN KEY ( ORDER_ID ) REFERENCES MEMBER_ORDER (ID),
    FOREIGN KEY ( PRODUCT_ID ) REFERENCES PRODUCT (ID)
    ) COMMENT = 'ORDER_LIST';


DROP TABLE IF EXISTS DELIVERY;
CREATE TABLE IF NOT EXISTS DELIVERY
(
    ID    VARCHAR(50) NOT NULL COMMENT '배송번호',
    ORDER_ID    VARCHAR(50) NOT NULL COMMENT '주문번호',
    STATUS    VARCHAR(50) NOT NULL COMMENT '배송상태',
    TRACKING_NUMBER    VARCHAR(50) NOT NULL COMMENT '운송장번호',
    PRIMARY KEY ( ID ),
    FOREIGN KEY ( ORDER_ID ) REFERENCES MEMBER_ORDER (ID)
    ) COMMENT = 'DELIVERY';


DROP TABLE IF EXISTS PLACING_ORDER;
CREATE TABLE IF NOT EXISTS PLACING_ORDER
(
    ID    VARCHAR(50) NOT NULL COMMENT '발주번호',
    PRODUCT_ID    VARCHAR(50) NOT NULL COMMENT '상품번호',
    ORDER_DATE    DATETIME NOT NULL COMMENT '발주일',
    INWAREHOUSEYN    VARCHAR(50) NOT NULL COMMENT '입고여부',
    PRIMARY KEY ( ID ),
    FOREIGN KEY ( PRODUCT_ID ) REFERENCES PRODUCT (ID)
    ) COMMENT = 'PLACING_ORDER';


DROP TABLE IF EXISTS INWAREHOUSE;
CREATE TABLE IF NOT EXISTS INWAREHOUSE
(
    ID    VARCHAR(50) NOT NULL COMMENT '입고번호',
    PRODUCT_ID    VARCHAR(50) NOT NULL COMMENT '상품번호',
    IN_DATE    DATETIME NOT NULL COMMENT '입고일',
    PRIMARY KEY ( ID ),
    FOREIGN KEY ( PRODUCT_ID ) REFERENCES PRODUCT (ID)
    ) COMMENT = 'INWAREHOUSE';


DROP TABLE IF EXISTS OUTWAREHOUSE;
CREATE TABLE IF NOT EXISTS OUTWAREHOUSE
(
    ID    VARCHAR(50) NOT NULL COMMENT '출고번호',
    ORDER_NUMBER    VARCHAR(50) NOT NULL COMMENT '주문번호',
    PRODUCT_ID    VARCHAR(50) NOT NULL COMMENT '상품번호',
    OUT_DATE    DATETIME NOT NULL COMMENT '출고일',
    ADDRESS    VARCHAR(50) NOT NULL COMMENT '주소',
    PRIMARY KEY ( ID ),
    FOREIGN KEY ( ORDER_NUMBER ) REFERENCES MEMBER_ORDER (ID),
    FOREIGN KEY ( PRODUCT_ID ) REFERENCES PRODUCT (ID)
    ) COMMENT = 'OUTWAREHOUSE';